# Source: https://github.com/projectdiscovery/nuclei-templates/blob/main/http/exposures/configs/git-config.yaml
# Modified: 仅保留核心路径，只读探测

id: git-config-exposed

info:
  name: Git Config Exposed
  author: pdteam
  severity: medium
  description: Detects exposed .git/config file.
  metadata:
    max-request: 1
  tags: http,exposure,git,sensitive-files

http:
  - method: GET
    path:
      - "{{BaseURL}}/.git/config"
    matchers:
      - type: word
        part: body
        words:
          - "[core]"
          - "repositoryformatversion"
        condition: and
