# Source: https://github.com/projectdiscovery/nuclei-templates/blob/main/http/exposures/configs/prometheus-metrics.yaml
# Modified: 收敛路径

id: prometheus-metrics-exposed

info:
  name: Prometheus Metrics Exposed
  author: pdteam
  severity: medium
  description: Detects exposed Prometheus metrics endpoint.
  metadata:
    max-request: 1
  tags: http,exposure,prometheus

http:
  - method: GET
    path:
      - "{{BaseURL}}/metrics"
    matchers:
      - type: word
        part: body
        words:
          - "# HELP"
          - "# TYPE"
        condition: and
